apiVersion: v1
kind: List
items:
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: pacman
    namespace: pacman
    labels:
      name: pacman
  spec:
    template:
      metadata:
        labels:
          name: pacman
      spec:
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 8080
            protocol: TCP
        selector:
          name: pacman
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: pacman
    namespace: pacman
  spec:
    clusterNames:
    - "null"
